#!/bin/bash

#         USAGE:  docker_generate_build -x prefix -p project_name -r repository_name
# 
#   DESCRIPTION:  This simple script will generate a docker 
#                 build command based in my structure (we decide 
#                 to use the format: prefix_project_name:git_tag, 
#                 maybe it's doesn't work properly to your infra, 
#                 but feel free to change or contact me. 
#                 PS.: But attention, use this script is your entirely responsibility.
# 
#        AUTHOR:  Alexandre Bargiela [ alexandre@bargiela.com.br ]
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  06/02/2015

function get_help(){
echo -e '
Usage: docker_generate_build -x prefix -p project_name -r repository_name

Options:
  -p        Set the project name located in your git repo or bitbucket whatever.
  -r        Set the repository name located in your git repo or bitbucket whatever.
  -x        Set prefix. 
  -h        Show help.
'
}

while getopts "x:p:r:h" opt; do
  case "$opt" in
    h)
      get_help
      exit 0
      ;;
    p)
      PROJECT=$OPTARG
      ;;
    r)
      EXTERNAL_REPO=$OPTARG
      ;;
    x)
      PREFIX=$OPTARG
      ;;
    *)
      get_help
      ;;
  esac
done

if [ ! -d ${HOME}/repos ]; then
  mkdir ${HOME}/repos;
fi
cd ${HOME}/repos

LOCAL_REPO=${HOME}/repos/${PROJECT}

if [ ! -d ${LOCAL_REPO} ]; then
  git clone git@bitbucket.org:${EXTERNAL_REPO}/${PROJECT}.git
  echo "docker build -t ${PREFIX}_${PROJECT}:$(git  --git-dir=${LOCAL_REPO}/.git describe|tr "+|*|#|$|@|=|&" "_") ."
else
  echo "docker build -t ${PREFIX}_${PROJECT}:$(git  --git-dir=${LOCAL_REPO}/.git describe|tr "+|*|#|$|@|=|&" "_") ."
fi

